name = "website-cf-d1"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./"

[[d1_databases]]
binding = "DB"
database_name = "items-db"
database_id = "a1aefe89-31c6-4a4a-ad23-40ff6a7fd368"

# Tambahkan bagian ini untuk logging
[build]
command = ""
[build.upload]
format = "directory"

# Aktifkan dev mode
[dev]
port = 8788

# Environment untuk development
[env.development]
# Konfigurasi khusus untuk development

# Environment untuk production
[env.production]
# Konfigurasi khusus untuk production